/**
 * Re-export barrel for the shared @alkazat/contracts handshake.
 *
 * The website's single integration surface with BE is `POST /signup/capture`.
 * Its request/response DTOs are owned by `@alkazat/contracts` (generated by the
 * BE thread), so we re-export them here rather than mirroring the shapes. This
 * keeps one source of truth and means the website can never silently drift from
 * the published contract.
 *
 * Note: the website's own `/api/signup` route returns a small UI-shaped result
 * (`{ ok, redirectUrl }`) to the browser form. That is the website's contract
 * with itself, not the BE handshake, so it is typed locally at its call sites
 * rather than here.
 */
export type { SignupCaptureRequest, SignupCaptureResponse } from '@alkazat/contracts';
