/**
 * The single integration surface for the website: the `POST /signup/capture`
 * request/response shape.
 *
 * Per the model context, this type is owned by `@yaycay/contracts` (generated by
 * the BE thread). Until that package is published and pinned here, this mirror
 * keeps the website honest about the handshake. Replace with the imported type
 * once `@yaycay/contracts` is available, do not let the two diverge.
 */

export interface SignupCaptureRequest {
  email: string;
  /** Explicit marketing consent captured at the form. */
  consent: boolean;
  /** Where the lead came from, for attribution (e.g. utm_source). */
  source?: string;
}

export interface SignupCaptureResponse {
  ok: boolean;
  /** The URL the visitor should be handed to (the app demo), if provided. */
  redirectUrl?: string;
}
